col: lc_cost

databricks:
  cols: ['databricks_cost']
  clients: ['soliver', 'lsag']

database:
  cols: ['database_cost', 'sql_size']
  clients: ['soliver', 'woehrl']

dataparameters:
  train_fraction: 0.9
  random_state: 5
  target_column: total_ipa_cost